### PR TITLE
remove connection retry limits, change how timeouts are handled

### PR DESCRIPTION
**Pull request by andyburke**
This is hopefully to mitigate issues like #101 and #110: it removes the limits on connection retries and will back off reconnect attempts up to a maximum timeout (15 minutes between connection attempts).

This PR will likely need some revisions and feedback is welcome.

### CODE REVIEW

**Comment by andyburke** [comment]
Ugh, I just realized my editor did some code reformatting. Is there perhaps a .jsbeautifyrc file I could use to get the formatting back?

**Comment by StephenHynes7** [comment]
Nice! The other thing we were looking at is https://github.com/juliangruber/reconnect-core, any thoughts on this approach?

**Comment by andyburke** [comment]
@StephenHynes7 Any battle-tested library would probably be preferable to the short take I did on this.

However, I will say that this is a problem we are currently seeing in production, so perhaps interim solutions should be on the table, depending on how long integrating a library like the one you link would take.

**Comment by ksullivan** [comment]
@andyburke @StephenHynes7 FYI I think the issue is still happening even with this change.

**Comment by StephenHynes7** [comment]
Yup (it was worth a shot) we confirmed this today, we have an internal dev looking at it at the moment, hope to make progress on resolving this particular issue very soon.

**Pull request merged**
