### PR TITLE
Update Babel, ESLint and drop npm-shrinkwrap

### PR DESCRIPTION
**Pull request by Souler**
As the title says. Updated the project to be built using babel 6 and (finally!) remove npm-shrinkwrap dependency.

### CODE REVIEW

**Comment by bathos** [comment]
Very nice, sorry I haven't had time to do this and glad someone else did. Not really thrilled with arbitrary changes to the eslintrc and style but I'll still go with it for now, since at least it's done.

**Comment by Souler** [comment]
Just to give some context about the eslint and style changes:
* `space-after-keywords` rule is replaced by `keyword-spacing` [Link](http://eslint.org/docs/rules/space-after-keywords).
* `space-return-throw-case` rule is replaced by `keyword-spacing` [Link](http://eslint.org/docs/rules/space-return-throw-case).
* `indent.indentSwitchCase` no longer exists. `SwitchCase` option is the way to go now [Link](http://eslint.org/docs/rules/indent#options).
* `curly` changed from `multi` to `multi-or-nest` because it was the config that reported the less problems when validating the current code.

**Comment by StephenHynes7** [comment]
@bathos  Has this been pushed to npm?

**Comment by bathos** [comment]
@StephenHynes7 nope, not yet -- I haven't been on my regular comp. Feel free to bump & publish if you have the time before I would. I think this would be a minor version, since nothing in the API has changed, while maybe it's a bit too much of a difference in dependencies to call a patch.

**Pull request merged**
