### PR TITLE
Update npm-shrinkwrap.json with all dependencies and devDependencies

### LINKED ISSUE #90: npm shrinkwrap results in extraneous package errors
when running npm shrinkwrap on my project that depends on le_node I get an extraneous package error and it fails to generate a valid npm-shrinkwrap.json. Here is the output of the shrinkwrap command:

 npm ERR! extraneous: mitm@1.1.0 D:\services\project\node_modules\le_node\node_modules\mitm
npm ERR! extraneous: winston@1.0.0 D:\services\project\node_modules\le_node\node_modules\winston
npm ERR! extraneous: bunyan@1.3.5 D:\services\project\node_modules\le_node\node_modules\bunyan
npm ERR! extraneous: tap-spec@3.0.0 D:\services\project\node_modules\le_node\node_modules\tap-spec
npm ERR! extraneous: tape@4.0.0 D:\services\project\node_modules\le_node\node_modules\tape
npm ERR! extraneous: gobble@0.10.2 D:\services\project\node_modules\le_node\node_modules\gobble
npm ERR! extraneous: gobble-babel@5.1.0 D:\services\project\node_modules\le_node\node_modules\gobble-babel
npm ERR! extraneous: gobble-cli@0.4.2 D:\services\project\node_modules\le_node\node_modules\gobble-cli

it looks like there are extra packages in the npm-shrinkwrap.json that are not included in the package.json as dependencies.

### PR DESCRIPTION
**Pull request by lledey**
Also bump outdated package.json version.
Fixes #90

### CODE REVIEW

**Comment by bathos** [comment]
False positive on the tests I'm afraid: `Cannot find module 'babel-core/lib/babel/tools/resolve-rc'`

**Comment by lledey** [comment]
Fixed the build, but tests are failing, it timeouts on network communications.
I had to update the `gobble-babel` module to fix the build, could this be the cause?

**Comment by bathos** [comment]
Yes, keeping gobble-babel locked was the entire reason for the
shrinkwrapping iirc.

**Comment by lledey** [comment]
Do you have any idea as to where to begin to look to fix that?

**Comment by Souler** [comment]
One idea. Would help adding npm-shrinkwrap.json to the .npmignore?
AFAIK the dependencies declared on npm-shrinkwrap are only necessary for building le_node, but the version you upload to npm repository is already built.

**Comment by JordanBelford** [comment]
Related: In the 1.1.2 release, codependency was update to 0.1.4 in package.json but not npm-shrinkwrap.json

**Comment by lledey** [comment]
Shrinkwrap has been removed upstream, closing

**Pull request closed without merging**
